### ISSUE TITLE
Mutualize backup buckets configuration between clusters

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1156]
k8ssandra-operator doesn’t expose a way of configuring backup buckets which can be reused by different clusters.
Instead, users are forced to repeat connection settings across multiple clusters.
We should instead create a new resource type to materialize reusable Medusa storage settings, which could be referenced in the K8ssandraCluster manifest.

```[tasklist]
### Tasks
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/1157
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/1158
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/1159
```

**Comment by rzvoncek** [comment]
Subtasks all done, closing the epic.
