### ISSUE TITLE
K8SSAND-1332 ⁃ Doc: Modify Install docs landing page to include links to cloud provider KO topics

### ISSUE THREAD

**Issue by johnsmartco** [k8ssandra/k8ssandra-operator#471]
**What happened?**

The current https://docs-v2.k8ssandra.io/install/ links to five **local install topics** (prereqs / single- and multi-cluster / helm and kustomize).  When GKE, AKS, and EKS topics are ready, update this Install landing page to link users to those additional topics.

**K8ssandra Operator version:**

 1.0.x

**Anything else we need to know?**:

Branch for edits should be based on `docs-v2` in k8ssandra/k8ssandra GH repo.

https://github.com/k8ssandra/k8ssandra/blob/docs-v2/docs/content/en/install/_index.md

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1332) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1332
┆priority: Medium

```[tasklist]
### Tasks
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/1043
- [ ] Create an installation guide for GKE
- [ ] Create an installation guide for AKS
- [ ] Create an installation guide for doks
```
